services:
  - type: web
    name: aineon-elite-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.4"
      - key: PORT
        value: 10000
    autoDeploy: true
