services:
  - type: web
    name: aineon-elite-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
