services:
  - type: web
    name: aineon-elite-dashboard
    env: node
    plan: free
    buildCommand: cd src && npm install
    startCommand: cd src && npm start
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: PORT
        value: 10000
    autoDeploy: true
